services:
  _defaults:
        autowire: true
        autoconfigure: true
        public: false

  Analogic\CryptocurrencyBundle\Daemon: ~
  Analogic\CryptocurrencyBundle\Bitcoind\TransactionFactory: ~
  Analogic\CryptocurrencyBundle\BitcoinCashd\TransactionFactory: ~
  Analogic\CryptocurrencyBundle\Litecoind\TransactionFactory: ~
  Analogic\CryptocurrencyBundle\Dashd\TransactionFactory: ~
  Analogic\CryptocurrencyBundle\Dogecoind\TransactionFactory: ~
  Analogic\CryptocurrencyBundle\Monerod\MonerodPoller: ~
  Analogic\CryptocurrencyBundle\Ethereumd\TransactionFactory: ~

  Analogic\CryptocurrencyBundle\Bitcoind\Bitcoind:
      arguments:
        - "%analogic_cryptocurrency.bitcoind.dsn%"
        - "%analogic_cryptocurrency.bitcoind.account%"
        - "%analogic_cryptocurrency.bitcoind.estimate_fees_blocks%"
        - "%analogic_cryptocurrency.bitcoind.minconf%"
        - "@Analogic\\CryptocurrencyBundle\\Bitcoind\\TransactionFactory"


  Analogic\CryptocurrencyBundle\Bitcoind\BitcoindListener:
      arguments:
        - "%analogic_cryptocurrency.bitcoind.listen%"
        - "%analogic_cryptocurrency.bitcoind.account%"

  Analogic\CryptocurrencyBundle\BitcoinCashd\BitcoinCashd:
      arguments:
        - "%analogic_cryptocurrency.bitcoincashd.dsn%"
        - "%analogic_cryptocurrency.bitcoincashd.account%"
        - "%analogic_cryptocurrency.bitcoincashd.estimate_fees_blocks%"
        - "%analogic_cryptocurrency.bitcoincashd.minconf%"

  Analogic\CryptocurrencyBundle\BitcoinCashd\BitcoinCashdListener:
      arguments:
        - "%analogic_cryptocurrency.bitcoincashd.listen%"
        - "%analogic_cryptocurrency.bitcoincashd.account%"

  Analogic\CryptocurrencyBundle\Litecoind\Litecoind:
      arguments:
        - "%analogic_cryptocurrency.litecoind.dsn%"
        - "%analogic_cryptocurrency.litecoind.account%"
        - "%analogic_cryptocurrency.litecoind.estimate_fees_blocks%"
        - 1

  Analogic\CryptocurrencyBundle\Litecoind\LitecoindListener:
      arguments:
        - "%analogic_cryptocurrency.litecoind.listen%"
        - "%analogic_cryptocurrency.litecoind.account%"

  Analogic\CryptocurrencyBundle\Dashd\Dashd:
      arguments:
        - "%analogic_cryptocurrency.dashd.dsn%"
        - "%analogic_cryptocurrency.dashd.account%"
        - "%analogic_cryptocurrency.dashd.estimate_fees_blocks%"
        - 1

  Analogic\CryptocurrencyBundle\Dashd\DashdListener:
      arguments:
        - "%analogic_cryptocurrency.dashd.listen%"
        - "%analogic_cryptocurrency.dashd.account%"

  Analogic\CryptocurrencyBundle\Dogecoind\Dogecoind:
      arguments:
        - "%analogic_cryptocurrency.dogecoind.dsn%"
        - "%analogic_cryptocurrency.dogecoind.account%"
        - "%analogic_cryptocurrency.dogecoind.estimate_fees_blocks%"
        - 1
  Analogic\CryptocurrencyBundle\Dogecoind\DogecoindListener:
      arguments:
        - "%analogic_cryptocurrency.dogecoind.listen%"
        - "%analogic_cryptocurrency.dogecoind.account%"

  Analogic\CryptocurrencyBundle\Monerod\Monerod:
      arguments:
        - "%analogic_cryptocurrency.monerod.dsn%"

  Analogic\CryptocurrencyBundle\Ethereumd\Ethereumd:
      arguments:
        - "%analogic_cryptocurrency.ethereumd.dsn%"
        - "%analogic_cryptocurrency.ethereumd.mother_account%"
        - "%analogic_cryptocurrency.ethereumd.password%"

  Analogic\CryptocurrencyBundle\BitcoinLnd\BitcoinLnd:
      arguments:
        - "%analogic_cryptocurrency.bitcoinlnd.dsn%"